### PR TITLE
Make changes so that can test pbrelease with alternative CCC code

### PR DESCRIPTION
**Pull request by martinholmer**
This pull request originated from [Package-Builder issue 165](https://github.com/PSLmodels/Package-Builder/issues/165), which was raised by @jdebacker.  Merging this pull request and creating a CCC release (probably 1.0.1) will provide an opportunity to test the ability of `pbrelease` to create working `ccc` packages.

### CODE REVIEW

**Comment by jdebacker** [comment]
@martinholmer Thanks for opening this PR.

I've not used a Makefile before.  Can you tell me what your workflow looks like when using this?   E.g., perhaps you can contrast it with my current way of working with this (and similar) models.  Here's what I've been doing when adding a feature:

* Do a `git status -uno` to check what branch I'm on and whether there are any uncommitted changes.
* If not, checkout a new branch to develop things.
* Activate the environment (the environment was probably created before and I generally let them get stale, only updating after some tests on Travis CI don't pass because of a change in a package dependency).
* `pip install -e .` to create the package
* Edit code, committing changes along the way (pushing to remote origin repo at end of work sessions to backup).
* Run `py.test module_name.py` as I finish edits to a function to test it as I go.
* When all changes made and committed, run full suite of tests with `pytest`.
* When done with changes and all tests pass, open a PR on GitHub.

It appears that the Makefile automates a fair bit of this, but I'm not sure exactly how it works.

**Comment by martinholmer** [comment]
At lunch right now. A short phone call about make is most efficient. Do you have time this afternoon?

**Comment by jdebacker** [comment]
@martinholmer Sure - give me a call any time before 4pm.

**Comment by martinholmer** [comment]
@jdebacker,  Thanks for provisionally merging pull request #263 and making release 1.0.1 that incorporates that pull request.  Given that you have done those things, I was able to test making and using `ccc` packages for release 1.0.1.   Everything went smoothly.  Here are the details of what I did on my computer working in my home directory (from which the Cost-of-Capital-Calculator source code is not visible):
```
iMac:~ mrh$ pbrelease Cost-of-Capital-Calculator ccc 1.0.1 
: Package-Builder will build model packages for:
:   repository_name = Cost-of-Capital-Calculator
:   package_name = ccc
:   model_version = 1.0.1
:   python_versions = ['3.6', '3.7']
: Package-Builder will upload model packages to:
:   Anaconda channel = pslmodels
:   using token in file = /Users/mrh/.pslmodels_anaconda_token
: Package-Builder is starting at Mon May 20 17:05:21 2019
: Package-Builder is cloning repository code for 1.0.1
Cloning into 'Cost-of-Capital-Calculator'...
remote: Enumerating objects: 142, done.
remote: Counting objects: 100% (142/142), done.
remote: Compressing objects: 100% (134/134), done.
remote: Total 142 (delta 7), reused 74 (delta 3), pack-reused 0
Receiving objects: 100% (142/142), 31.87 MiB | 12.01 MiB/s, done.
Resolving deltas: 100% (7/7), done.
Note: checking out '16653a8df14d1a1e9658d8aeace3560985dc14c5'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

: Package-Builder is setting version
: Package-Builder is building package for Python 3.6
No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.11
WARNING:conda_build.metadata:No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.11
INFO:conda_build.variants:Adding in variants from internal_defaults
INFO:conda_build.variants:Adding in variants from config.variant
INFO:conda_build.metadata:Attempting to finalize metadata for ccc
WARNING: symlink_conda() is deprecated.
zip_safe flag not set; analyzing archive contents...
ccc.__pycache__.data.cpython-36: module references __file__
ccc.__pycache__.parameters.cpython-36: module references __file__
ccc.__pycache__.utils.cpython-36: module references __file__
INFO:conda_build.build:Packaging ccc
INFO:conda_build.build:Packaging ccc-1.0.1-py36_0
/var/folders/1q/3c2zxn3n3tz2lxp5h842dkhh0000gn/T/tmp0effxtr4/ccc-1.0.1-py36_0.tar.bz2: C1115 Found invalid license "None" in info/index.json
INFO:conda_build.variants:Adding in variants from /var/folders/1q/3c2zxn3n3tz2lxp5h842dkhh0000gn/T/tmpytonl36x/info/recipe/conda_build_config.yaml
WARNING: symlink_conda() is deprecated.
: Package-Builder is converting package for Python 3.6
: Package-Builder is uploading packages for Python 3.6
Using Anaconda API: https://api.anaconda.org
Using "pslmodels" as upload username
Detecting file type...
File type is "conda"
Extracting package attributes for upload
Creating package "ccc"
Creating release "1.0.1"
Uploading file "pslmodels/ccc/1.0.1/osx-64/ccc-1.0.1-py36_0.tar.bz2"
 uploaded 2174 of 2174Kb: 100.00% ETA: 0.0 minutes
Upload complete
package located at:
https://anaconda.org/pslmodels/ccc

Using Anaconda API: https://api.anaconda.org
Using "pslmodels" as upload username
Detecting file type...
File type is "conda"
Extracting package attributes for upload
Creating package "ccc"
Creating release "1.0.1"
Uploading file "pslmodels/ccc/1.0.1/linux-64/ccc-1.0.1-py36_0.tar.bz2"
 uploaded 2178 of 2178Kb: 100.00% ETA: 0.0 minutes
Upload complete
package located at:
https://anaconda.org/pslmodels/ccc

Using Anaconda API: https://api.anaconda.org
Using "pslmodels" as upload username
Detecting file type...
File type is "conda"
Extracting package attributes for upload
Creating package "ccc"
Creating release "1.0.1"
Uploading file "pslmodels/ccc/1.0.1/win-32/ccc-1.0.1-py36_0.tar.bz2"
 uploaded 2178 of 2178Kb: 100.00% ETA: 0.0 minutes
Upload complete
package located at:
https://anaconda.org/pslmodels/ccc

Using Anaconda API: https://api.anaconda.org
Using "pslmodels" as upload username
Detecting file type...
File type is "conda"
Extracting package attributes for upload
Creating package "ccc"
Creating release "1.0.1"
Uploading file "pslmodels/ccc/1.0.1/win-64/ccc-1.0.1-py36_0.tar.bz2"
 uploaded 2176 of 2176Kb: 100.00% ETA: 0.0 minutes
Upload complete
package located at:
https://anaconda.org/pslmodels/ccc

: Package-Builder is building package for Python 3.7
No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.11
WARNING:conda_build.metadata:No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.11
INFO:conda_build.variants:Adding in variants from internal_defaults
INFO:conda_build.variants:Adding in variants from config.variant
INFO:conda_build.metadata:Attempting to finalize metadata for ccc
WARNING: symlink_conda() is deprecated.
zip_safe flag not set; analyzing archive contents...
ccc.__pycache__.data.cpython-37: module references __file__
ccc.__pycache__.parameters.cpython-37: module references __file__
ccc.__pycache__.utils.cpython-37: module references __file__
INFO:conda_build.build:Packaging ccc
INFO:conda_build.build:Packaging ccc-1.0.1-py37_0
/var/folders/1q/3c2zxn3n3tz2lxp5h842dkhh0000gn/T/tmp3pdav862/ccc-1.0.1-py37_0.tar.bz2: C1115 Found invalid license "None" in info/index.json
INFO:conda_build.variants:Adding in variants from /var/folders/1q/3c2zxn3n3tz2lxp5h842dkhh0000gn/T/tmplusogh58/info/recipe/conda_build_config.yaml
WARNING: symlink_conda() is deprecated.
: Package-Builder is converting package for Python 3.7
: Package-Builder is uploading packages for Python 3.7
Using Anaconda API: https://api.anaconda.org
Using "pslmodels" as upload username
Detecting file type...
File type is "conda"
Extracting package attributes for upload
Creating package "ccc"
Creating release "1.0.1"
Uploading file "pslmodels/ccc/1.0.1/osx-64/ccc-1.0.1-py37_0.tar.bz2"
 uploaded 2171 of 2171Kb: 100.00% ETA: 0.0 minutes
Upload complete
package located at:
https://anaconda.org/pslmodels/ccc

Using Anaconda API: https://api.anaconda.org
Using "pslmodels" as upload username
Detecting file type...
File type is "conda"
Extracting package attributes for upload
Creating package "ccc"
Creating release "1.0.1"
Uploading file "pslmodels/ccc/1.0.1/linux-64/ccc-1.0.1-py37_0.tar.bz2"
 uploaded 2178 of 2178Kb: 100.00% ETA: 0.0 minutes
Upload complete
package located at:
https://anaconda.org/pslmodels/ccc

Using Anaconda API: https://api.anaconda.org
Using "pslmodels" as upload username
Detecting file type...
File type is "conda"
Extracting package attributes for upload
Creating package "ccc"
Creating release "1.0.1"
Uploading file "pslmodels/ccc/1.0.1/win-32/ccc-1.0.1-py37_0.tar.bz2"
 uploaded 2178 of 2178Kb: 100.00% ETA: 0.0 minutes
Upload complete
package located at:
https://anaconda.org/pslmodels/ccc

Using Anaconda API: https://api.anaconda.org
Using "pslmodels" as upload username
Detecting file type...
File type is "conda"
Extracting package attributes for upload
Creating package "ccc"
Creating release "1.0.1"
Uploading file "pslmodels/ccc/1.0.1/win-64/ccc-1.0.1-py37_0.tar.bz2"
 uploaded 2176 of 2176Kb: 100.00% ETA: 0.0 minutes
Upload complete
package located at:
https://anaconda.org/pslmodels/ccc

: Package-Builder is cleaning-up
: Package-Builder is finishing at Mon May 20 17:09:55 2019

iMac:~ mrh$ conda search -c PSLmodels ccc
Loading channels: done
# Name                       Version           Build  Channel             
ccc                            0.2.9          py36_0  PSLmodels           
ccc                            1.0.0            py_0  PSLmodels           
ccc                            1.0.1          py36_0  PSLmodels           
ccc                            1.0.1          py37_0  PSLmodels           

iMac:~ mrh$ ~/packages 
# packages in environment at /Users/mrh/anaconda3:
#
# Name                    Version                   Build  Channel
pkgbld                    0.22.0                   py36_0    PSLmodels
iMac:~ mrh$ conda install -c PSLmodels ccc
Collecting package metadata: done
Solving environment: done

## Package Plan ##
  environment location: /Users/mrh/anaconda3

  added / updated specs:
    - ccc

The following packages will be downloaded:
    package                    |            build
    ---------------------------|-----------------
    taxcalc-2.2.0              |           py36_0        34.1 MB  PSLmodels
    ------------------------------------------------------------
                                           Total:        34.1 MB

The following NEW packages will be INSTALLED:
  ccc                PSLmodels/osx-64::ccc-1.0.1-py36_0
  taxcalc            PSLmodels/osx-64::taxcalc-2.2.0-py36_0

Proceed ([y]/n)? y

Downloading and Extracting Packages
taxcalc-2.2.0        | 34.1 MB   | ##################################### | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done


iMac:~ mrh$ ~/packages 
# packages in environment at /Users/mrh/anaconda3:
#
# Name                    Version                   Build  Channel
ccc                       1.0.1                    py36_0    PSLmodels
pkgbld                    0.22.0                   py36_0    PSLmodels
taxcalc                   2.2.0                    py36_0    PSLmodels


iMac:~ mrh$ cp work/PSL/Cost-of-Capital-Calculator/example.py .


iMac:~ mrh$ head example.py 
"""
Runs Cost-of-Capital-Calculator with TCJA as baseline and 2017 law as reform
----------------------------------------------------------------------------
"""
# import support packages and Cost-of-Capital-Calculator classes and function
import os
from bokeh.io import show
import taxcalc
from ccc.data import Assets
from ccc.parameters import Specification


iMac:~ mrh$ python example.py 


iMac:~ mrh$ ls -l *csv
-rw-r--r--  1 mrh  staff  63812 May 20 17:13 baseline_byasset.csv
-rw-r--r--  1 mrh  staff  42905 May 20 17:13 baseline_byindustry.csv
-rw-r--r--  1 mrh  staff  61298 May 20 17:13 changed_byasset.csv
-rw-r--r--  1 mrh  staff  41434 May 20 17:13 changed_byindustry.csv
-rw-r--r--  1 mrh  staff  63712 May 20 17:13 reform_byasset.csv
-rw-r--r--  1 mrh  staff  43006 May 20 17:13 reform_byindustry.csv


iMac:~ mrh$ diff changed_byasset.csv work/PSL/Cost-of-Capital-Calculator/example_output/changed_byasset_expected.csv


iMac:~ mrh$ diff changed_byindustry.csv work/PSL/Cost-of-Capital-Calculator/example_output/changed_byindustry_expected.csv
```

**Comment by jdebacker** [comment]
@martinholmer Excellent - glad to hear that Package Builder could create the CCC package!  Thanks for your efforts on this.

**Pull request merged**
