### PR TITLE
COMP output

### PR DESCRIPTION
**Pull request by jdebacker**
This PR updates CCC to be compliant with [COMP Models](https://comp-org.github.io/comp-ce/) and adds scripts to run on COMP.

### CODE REVIEW

**Comment by hdoupe** [comment]
#250 looks good to me @jdebacker. I have a couple suggestions:
- Rename the top-level folder to lowercase `comp` instead of `COMP`. It seems like that would make the `comp` folder less intrusive in your repo.
- Add an `install.sh` script to the `comp` directory. For CCC, I think it would just be `conda install ccc -c pslmodels`.
- Rename `ccc_comp.py` to `functions.py` and `tests/test_comp.py` to `tests/test_functions.py`.

The way I see this working is you provide a link to your repo, COMP automatically downloads `install.sh`, `functions.py`, and `tests/test_functions.py`, builds the environment from `install.sh`, runs the tests in `tests/test_function.py`, and deploys if the tests pass successfully or returns an error report otherwise.

Do these changes seem OK to you?

**Comment by jdebacker** [comment]
@hdoupe Thanks for the suggestions.  I'll make these changes.

**Comment by hdoupe** [comment]
Great, thanks @jdebacker.

**Comment by jdebacker** [comment]
@hdoupe.  I've made this changes.  When I run `pytest` on the `comp\tests` folder, I'm getting the following error and am unsure of the fix:

```
(ccc-dev) A02655JDEBACKER:comp jason.debacker$ pytest
============================= test session starts ==============================
platform darwin -- Python 3.6.8, pytest-4.4.1, py-1.8.0, pluggy-0.9.0
rootdir: /Users/jason.debacker/repos/Cost-of-Capital-Calculator, inifile: setup.cfg
plugins: xdist-1.26.1, pep8-1.0.6, forked-1.0.2
collected 1 item / 1 errors

==================================== ERRORS ====================================
________________ ERROR collecting comp/tests/test_functions.py _________________
/anaconda3/envs/ccc-dev/lib/python3.6/site-packages/_pytest/runner.py:226: in from_call
    result = func()
/anaconda3/envs/ccc-dev/lib/python3.6/site-packages/_pytest/runner.py:253: in <lambda>
    call = CallInfo.from_call(lambda: list(collector.collect()), "collect")
/anaconda3/envs/ccc-dev/lib/python3.6/site-packages/_pytest/python.py:726: in collect
    "__init__ constructor" % self.obj.__name__
/anaconda3/envs/ccc-dev/lib/python3.6/site-packages/_pytest/nodes.py:136: in warn
    lineno=lineno + 1 if lineno is not None else None,
E   _pytest.warning_types.PytestWarning: cannot collect test class 'TestFunctions' because it has a __init__ constructor
!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!
=========================== 1 error in 16.30 seconds ===========================
```

Any suggestions?

**Comment by hdoupe** [comment]
I'm going to rename `TestFunctions` to `FunctionsTest` so that py.test doesn't pick it up. py.test doesn't like it when test classes have an `__init__` constructor.

**Comment by hdoupe** [comment]
I just updated the master branch for `compdevkit` to use `FunctionsTest`.

**Comment by jdebacker** [comment]
@hdoupe File directory and names have been changed per your suggestion.  I not import the new COMP test class and the `test_functions.py` all pass.

**Comment by hdoupe** [comment]
Awesome, these changes look good to me. I'll make changes on the COMP side to get CCC up in the coming days.

**Pull request merged**
