### PR TITLE
Update retrieve_puf function

### PR DESCRIPTION
**Pull request by jdebacker**
This PR updates the `retrieve_puf` function used in the Compute Studio app to access the PUF.

cc @hdoupe

### CODE REVIEW

**Comment by jdebacker** [comment]
@hdoupe Please review this and let me know if it's good to merge.  Thanks!

**Comment by hdoupe** [comment]
@jdebacker I'm testing this locally now. Thanks for pulling the changes from my pr over. Will report back when the tests are done.

**Comment by hdoupe** [comment]
@jdebacker LGTM! Tests pass locally and am able to read the PUF file.

**Comment by jdebacker** [comment]
Thanks @hdoupe!  Merging now -- feel free to update app whenever.

**Comment by hdoupe** [comment]
@jdebacker this is live on CCC now and working as expected!

**Pull request merged**
