### PR TITLE
Use Policy object straight away

### PR DESCRIPTION
**Pull request by jdebacker**
This PR tries to fix the issue of Tax-Calculator parameters not showing up on the CCC app:
Screen Shot 2020-11-29 at 9 44 13 PM

It does this by using the Tax-Calculator `Policy` object directly - rather than reading in a default parameters JSON.  I think moving from Tax-Calculator 2.9 to 3.0 makes the later method fail.

cc @hdoupe

### CODE REVIEW

**Comment by jdebacker** [comment]
@hdoupe, I am getting one test failure with this change.   It is in the `test_functions.py::TestFunctions1::test_get_inputs` test.  Here's the last part of the traceback:

```
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

model_parameters = {'Business Tax Parameters': {'BonusDeprec_10yr': OrderedDict([('title', 'Bonus depreciation rate on 10-year class prop...', {'puf': False, 'cps': True}), ('section_1', 'Benefits'), ('section_2', 'Benefit Repeal'), ('indexable', False)]))])}

    def load_model_parameters(model_parameters):
        for sect, _defaults in model_parameters.items():
            try:
                type(f"Params{sect}", (Parameters,), {"defaults": _defaults})()
            except Exception as ser_exception:
>               raise CSKitError(
                    f"An error was thrown while loading the model parameters for section: '{sect}'."
                    f"\n\n\t Hint: Make sure you are using the 'Parameters.dump' method if you are "
                    f"using ParamTools.\n\n{str(ser_exception)}"
                ) from ser_exception
E               cs_kit.exceptions.CSKitError: An error was thrown while loading the model parameters for section: 'Individual and Payroll Tax Parameters'.
E
E               	 Hint: Make sure you are using the 'Parameters.dump' method if you are using ParamTools.
E
E               2020

../../../../anaconda3/envs/ccc-dev/lib/python3.8/site-packages/cs_kit/validate.py:22: CSKitError
```

**Comment by jdebacker** [comment]
@hdoupe With latest commit, all tests are passing.

I added an `inputs.py` script as in the Tax-Cruncher project and things seem to be working ok now.  All tests passing, output generated as expected.

**Comment by hdoupe** [comment]
@jdebacker I just opened a PR to this branch here: https://github.com/jdebacker/Cost-of-Capital-Calculator/pull/5

**Comment by jdebacker** [comment]
Thanks for the PR to this branch @hdoupe.  Much more elegant.

I'm running test locally (Travis CI doesn't seem to be running any more for this repo) and will merge when all tests pass.

**Comment by hdoupe** [comment]
Sounds good @jdebacker!

**Pull request merged**
