### PR TITLE
Add more output to C/S app

### PR DESCRIPTION
**Pull request by jdebacker**
This PR adds more output to the Compute Studio app for CCC.  The output page will now include 3 plots and one table.  The download will not have 3 csv files so that users can have the most detailed output from the model to look at changes by industry and asset.

### CODE REVIEW

**Comment by jdebacker** [comment]
@hdoupe How do these changes look to you?

When I run the `write_output.py` script you send, I get html files for only two of the three Bokeh plots - and those html files just show the title, not the plot.  The table renders as expected.  Does this seem right?

**Comment by hdoupe** [comment]
@jdebacker my hunch is that there is some kind of bokeh version mismatch issue. I'm happy to run locally though. Would you mind posting The Script (ha, I should include this in the docs!).

**Comment by jdebacker** [comment]
@hdoupe Here's the script I'm using:
```
from cs_config import functions
import cs_storage
from cs_storage.screenshot import write_template
from ccc.parameters import Specification, DepreciationParams
from ccc.data import Assets
from ccc.calculator import Calculator

'''
This script is useful to testing the outputs from the cs_config/functions.py
script. 
'''

# Create baseline policy Calculator object
p = Specification()
assets = Assets()
dp = DepreciationParams()
calc1 = Calculator(p, dp, assets)
# Create another policy
p2 = Specification()
p2.update_specification({'CIT_rate': 0.35})
calc2 = Calculator(p2, dp, assets)

# outputs = functions.run_model(meta_param_dict, adjustment_dict)
outputs = functions.comp_output(
    calc1, calc2, out_var='mettr')

i = 1
for output in outputs["renderable"]:
    serializer = cs_storage.get_serializer(output["media_type"])
    ser = serializer.serialize(output["data"])
    deserialized = dict(
        output, data=serializer.deserialize(ser, json_serializable=True)
    )
    res = write_template(deserialized)
    with open(f"{output['title']}.html", "w") as f:
        f.write(res)
    i += 1
```

**Comment by hdoupe** [comment]
@jdebacker I added an id to each output and then the bokeh charts rendered as expected:

```python
from cs_config import functions
import cs_storage
from cs_storage.screenshot import write_template
from ccc.parameters import Specification, DepreciationParams
from ccc.data import Assets
from ccc.calculator import Calculator

'''
This script is useful to testing the outputs from the cs_config/functions.py
script. 
'''

# Create baseline policy Calculator object
p = Specification()
assets = Assets()
dp = DepreciationParams()
calc1 = Calculator(p, dp, assets)
# Create another policy
p2 = Specification()
p2.update_specification({'CIT_rate': 0.35})
calc2 = Calculator(p2, dp, assets)

# outputs = functions.run_model(meta_param_dict, adjustment_dict)
outputs = functions.comp_output(
    calc1, calc2, out_var='mettr')

i = 1
for output in outputs["renderable"]:
    serializer = cs_storage.get_serializer(output["media_type"])
    ser = serializer.serialize(output["data"])
    deserialized = dict(
        output, data=serializer.deserialize(ser, json_serializable=True)
    )
    deserialized["id"] = f"test-{i}"  # Need this output id.
    res = write_template(deserialized)
    with open(f"{output['title']}.html", "w") as f:
        f.write(res)
    i += 1
```

**Comment by jdebacker** [comment]
Excellent - thanks @hdoupe!

This PR should be ready - will leave open for bit and build new package for C/S after merged.

**Pull request merged**
