### PR TITLE
Remove Unused Dependency: psutil

### PR DESCRIPTION
**Pull request by gdrosos**
## Summary

This pull request removes the unused dependency `psutil` from the `setup.py`  configuration file . This detection and removal is a finding from ongoing research aimed at identifying and eliminating code bloat within software projects.

## Rationale

The `psutil` library was introduced  in a6d60a7e. However, an examination of the current codebase revealed that it is not used within the project. Removing this unused dependency can reduce the overall footprint of the application, mitigate potential security risks, and simplify the dependency management process.

## Changes

- Removed the `psutil`  dependency from the `setup.py` file.

## Impact

- Reduced package size: Eliminating this unused dependency will decrease the overall size of the installed packages.

- Simplified dependency tree: A leaner list of dependencies aids in more straightforward project maintenance and faster installations.

### CODE REVIEW

**Comment by gdrosos** [comment]
Hello @rickecon, @jdebacker 

I hope this message finds you well. We are currently engaged in a research project focused on optimizing projects by identifying and eliminating unnecessary dependencies. Your insights and expertise as  maintainers would greatly contribute to our research efforts.

Could you please take a moment to review these changes? Your input would be highly valuable to us.

Thank you for your consideration!

**Comment by jdebacker** [comment]
@gdrosos I saw an error in the units tests run under CI with this PR.  I've fixed those in PR #378.  

Can you sync to the master branch and then this PR should pass tests and I will merge.

Thanks!

**Comment by gdrosos** [comment]
Thanks @jdebacker, I just synced the fork to the master branch

**Comment by jdebacker** [comment]
Thanks for this PR @gdrosos! Merging.

**Pull request merged**
